services:
  app:
    image: oven/bun

    volumes:
      - ./app:/app

    working_dir: /app

    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "5400:5400"

    environment:
      - JOPIN_WEBSOCKET_PORT=5400

    command: sh -c "chmod +x ./start.sh && ./start.sh"